name: fortnox-api

services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    restart: on-failure
    networks:
      - fortnox-network

  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8300:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d
    networks:
      - fortnox-network

networks:
  fortnox-network:
    driver: bridge